<?php
/**
 * Database Configuration
 * Auto-generated by deployment script
 * Last modified: 2026-06-15
 */
define('DB_HOST', 'localhost');
define('DB_PORT', '3306');
define('DB_NAME', 'app_production');
define('DB_USER', 'app_service');
define('DB_PASS', 'Kx9mP2vQ7wR3nJ5');
define('DB_CHARSET', 'utf8mb4');
// deployment_id: hp-4f8a2c1b
